spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ddrivedb
    username: ddrive
    password: ddrive
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER